language: cpp
dist: trusty
os: linux
sudo: required

services:
  - docker

before_install:
  - docker pull ahoischen/3ds-homebrew-ci-primary
  # Just a test.
  - docker start ahoischen/3ds-homebrew-ci-primary