version: 2
jobs:
  build:
    docker:
      - image: "ahoischen/3ds-homebrew-ci-primary:0.0.3"
        environment:
          TEST_EXIT_FILE: "${CITRA_SDMC}/Test Finished.bin"
          TEST_LOG_FILE: "${CITRA_SDMC}/Test Log.txt"
          CIRCLE_ARTIFACTS: "/tmp/artifacts"
          CIRCLE_TEST_REPORTS: ${CIRCLE_ARTIFACTS}/reports"

    working_directory: ~/work
    steps:
      - run:
          name: Create output directories
          command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - checkout

        # Starting before compile eliminates the need to wait.
      - run: 
          name: Start display for citra
          command: sudo /usr/bin/supervisord -c /etc/supervisor/supervisord.conf |& tee $CIRCLE_ARTIFACTS/supervisord
          background: true

      - run:
          name: Compile
          command: |
            mkdir -p build &&
            cd build &&
            cmake -DCMAKE_TOOLCHAIN_FILE=DevkitArm3DS.cmake .. |& tee $CIRCLE_ARTIFACTS/cmake &&
            make |& tee $CIRCLE_ARTIFACTS/make &&
            cd ..

      - run:
          name: Test
          command: |
            citra build/test_runner.3dsx |& tee $CIRCLE_ARTIFACTS/citra;
            mkdir -p "${CIRCLE_TEST_REPORTS}/reports"
            cp "$TEST_LOG_FILE" "$CIRCLE_TEST_REPORTS/reports/junit.xml" &&
            cat "$TEST_LOG_FILE" &&
            exit `cat "$TEST_EXIT_FILE" || false`

      - store_test_results:
          path: $CIRCLE_TEST_REPORTS

      - store_artifacts:
          path: $CIRCLE_ARTIFACTS
          when: always